services:
  - type: web
    name: carrent-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: ASPNETCORE_HTTP_PORTS
        value: 8080
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: SUPABASE_DB_CONNECTION
        sync: false
      - key: JwtSettings__SecretKey
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
