CREATE DATABASE CarRentDb;
GO
USE CarRentDb;
GO

CREATE TABLE Roles (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL UNIQUE,
    Description NVARCHAR(250) NULL,
    IsSystem BIT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Users (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    FirstName NVARCHAR(120) NOT NULL,
    LastName NVARCHAR(120) NOT NULL,
    Email NVARCHAR(250) NOT NULL UNIQUE,
    PhoneNumber NVARCHAR(40) NULL,
    PasswordHash NVARCHAR(500) NOT NULL,
    RefreshToken NVARCHAR(500) NULL,
    RefreshTokenExpiryTime DATETIME2 NULL,
    IsEmailVerified BIT NOT NULL DEFAULT 0,
    IsActive BIT NOT NULL DEFAULT 1,
    RoleId UNIQUEIDENTIFIER NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL,
    CONSTRAINT FK_Users_Roles FOREIGN KEY (RoleId) REFERENCES Roles(Id)
);

CREATE TABLE Branches (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Name NVARCHAR(150) NOT NULL UNIQUE,
    City NVARCHAR(120) NOT NULL,
    State NVARCHAR(120) NOT NULL,
    Country NVARCHAR(120) NOT NULL,
    Address NVARCHAR(300) NOT NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Vehicles (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    RegistrationNumber NVARCHAR(50) NOT NULL UNIQUE,
    Vin NVARCHAR(80) NOT NULL,
    Make NVARCHAR(120) NOT NULL,
    Model NVARCHAR(120) NOT NULL,
    Year INT NOT NULL,
    FuelType NVARCHAR(50) NOT NULL,
    Transmission NVARCHAR(50) NOT NULL,
    SeatingCapacity INT NOT NULL,
    DailyRate DECIMAL(18,2) NOT NULL,
    IsAvailable BIT NOT NULL DEFAULT 1,
    BranchId UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT FK_Vehicles_Branches FOREIGN KEY (BranchId) REFERENCES Branches(Id)
);

CREATE TABLE Bookings (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    CustomerId UNIQUEIDENTIFIER NOT NULL,
    VehicleId UNIQUEIDENTIFIER NOT NULL,
    BookingDate DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    StartDate DATETIME2 NOT NULL,
    EndDate DATETIME2 NOT NULL,
    TotalAmount DECIMAL(18,2) NOT NULL,
    Status NVARCHAR(60) NOT NULL,
    Notes NVARCHAR(500) NULL,
    CONSTRAINT FK_Bookings_Vehicles FOREIGN KEY (VehicleId) REFERENCES Vehicles(Id)
);
GO
