-- SQL Server object model delivered alongside EF Core entities for the database design.
-- This file intentionally mirrors the core normalized tables required by the requested rental platform.

CREATE TABLE Permissions (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Name NVARCHAR(120) NOT NULL UNIQUE,
    Description NVARCHAR(250) NULL
);

CREATE TABLE RolePermissions (
    RoleId UNIQUEIDENTIFIER NOT NULL,
    PermissionId UNIQUEIDENTIFIER NOT NULL,
    PRIMARY KEY (RoleId, PermissionId)
);

CREATE TABLE Customers (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    KycStatus NVARCHAR(60) NOT NULL DEFAULT 'Pending',
    WalletBalance DECIMAL(18,2) NOT NULL DEFAULT 0,
    LoyaltyPoints INT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Drivers (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    LicenseNumber NVARCHAR(60) NOT NULL UNIQUE,
    KycStatus NVARCHAR(60) NOT NULL DEFAULT 'Pending',
    Rating DECIMAL(3,2) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE VehicleCategories (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Name NVARCHAR(120) NOT NULL UNIQUE,
    Description NVARCHAR(250) NULL
);

CREATE TABLE Brands (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Name NVARCHAR(120) NOT NULL UNIQUE
);

CREATE TABLE Models (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    BrandId UNIQUEIDENTIFIER NOT NULL,
    Name NVARCHAR(120) NOT NULL,
    CategoryId UNIQUEIDENTIFIER NOT NULL
);

CREATE TABLE Payments (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    BookingId UNIQUEIDENTIFIER NOT NULL,
    Amount DECIMAL(18,2) NOT NULL,
    Gateway NVARCHAR(80) NOT NULL,
    Status NVARCHAR(60) NOT NULL,
    PaidAt DATETIME2 NULL
);

CREATE TABLE Refunds (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    BookingId UNIQUEIDENTIFIER NOT NULL,
    Amount DECIMAL(18,2) NOT NULL,
    Status NVARCHAR(60) NOT NULL,
    ProcessedAt DATETIME2 NULL
);

CREATE TABLE Coupons (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Code NVARCHAR(60) NOT NULL UNIQUE,
    DiscountAmount DECIMAL(18,2) NOT NULL,
    IsActive BIT NOT NULL DEFAULT 1
);

CREATE TABLE VehicleMaintenance (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    VehicleId UNIQUEIDENTIFIER NOT NULL,
    ServiceType NVARCHAR(120) NOT NULL,
    ScheduledOn DATETIME2 NOT NULL,
    Status NVARCHAR(60) NOT NULL,
    Cost DECIMAL(18,2) NULL
);

CREATE TABLE Insurance (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    VehicleId UNIQUEIDENTIFIER NOT NULL,
    PolicyNumber NVARCHAR(120) NOT NULL UNIQUE,
    ExpiryDate DATETIME2 NOT NULL,
    Provider NVARCHAR(120) NOT NULL
);

CREATE TABLE FuelLogs (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    VehicleId UNIQUEIDENTIFIER NOT NULL,
    LoggedOn DATETIME2 NOT NULL,
    Quantity DECIMAL(18,2) NOT NULL,
    Cost DECIMAL(18,2) NOT NULL
);

CREATE TABLE Documents (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    EntityType NVARCHAR(80) NOT NULL,
    EntityId UNIQUEIDENTIFIER NOT NULL,
    DocumentType NVARCHAR(80) NOT NULL,
    StoragePath NVARCHAR(300) NOT NULL,
    UploadedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Reviews (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    CustomerId UNIQUEIDENTIFIER NOT NULL,
    VehicleId UNIQUEIDENTIFIER NOT NULL,
    Rating INT NOT NULL,
    Comment NVARCHAR(500) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Notifications (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    NotificationType NVARCHAR(80) NOT NULL,
    Message NVARCHAR(500) NOT NULL,
    IsRead BIT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE AuditLogs (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NULL,
    Action NVARCHAR(120) NOT NULL,
    EntityType NVARCHAR(120) NOT NULL,
    EntityId UNIQUEIDENTIFIER NULL,
    Payload NVARCHAR(MAX) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Settings (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    KeyName NVARCHAR(120) NOT NULL UNIQUE,
    KeyValue NVARCHAR(500) NOT NULL,
    Category NVARCHAR(120) NOT NULL,
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO
